development:
  adapter: postgresql
  encoding: utf8
  database: css_koans_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: css_koans_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: css_koans_production
  pool: 5
  username:
  password:
